config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :followers, only: [:create, :destroy], param: :user_id

  resources :posts do
    collection do
      get 'explore'
      get 'tagged'
    end
    resource :likes, only: [:create, :destroy], module: :posts
    resources :comments, only: [:create, :new, :show, :destroy], module: :posts
  end

  resources :users, only: [:show], param: :username, path: '' do
    resources :posts, only: [:show], module: :users
  end

  # get 'posts/tagged', to: "posts#tagged", as: :tagged

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validates :image, attached: true

  scope :of_followed_users, -> (following_users) { where(user_id: following_users) }

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  accepts_nested_attributes_for :comments, reject_if: proc { |attributes| attributes['body'].blank? }

  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  has_one_attached :avatar

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy
  has_many :following, through: :following_relationships, source: :following

  def likes?(likeable)
    likeable.likes.where(user_id: id).any?
  end

  def follow(user_id)
    following_relationships.find_or_create_by(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.where(following_id: user_id).destroy_all
  end

  def follows?(user_id)
    following_relationships.where(following_id: user_id).any?
  end
end

app/controllers/posts/comments_controller.rb
module Posts
  class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @comment = @post.comments.build(comments_params.merge(user: current_user))

      if @comment.save
        PostCommentChannel.broadcast_to(@post, comment_created_params)
        # render partial: 'posts/comments/comment', locals: { comment: @comment }
      else
        render partial: 'posts/comments/error', locals: { comment: @comment }, status: :bad_request
      end
    end

    def show
      @comments = @post.comments
        .where("created_at < ?", DateTime.parse(params[:last_result_timestamp]))
        .order(created_at: :desc)
        .limit(5)
    end

    def destroy
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      PostCommentChannel.broadcast_to(@post, comment_destroyed_params)
    end

    private

    def comment_destroyed_params
      { action: :destroy, comment_id: @comment.id }
    end

    def comment_created_params
      { action: :created, html: comment_html }
    end

    def comment_html
      ApplicationController.renderer.render(
        partial: "posts/comments/comment",
        locals: { comment: @comment, realtime: true },
        format: :html
      )
    end

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comments_params
      params.require(:comment).permit(:body)
    end
  end
end

app/controllers/posts/likes_controller.rb
module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @post.likes.where(user: current_user).first_or_create

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    def destroy
      @post.likes.where(user: current_user).destroy_all

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.of_followed_users(current_user.following).with_attached_image.order(created_at: :desc)
  end

  def explore
    @posts = Post.with_attached_image.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.comments&.first&.user = current_user

    if @post.save
      redirect_to posts_path, notice: "Created Post"
    else
      render :new, notice: "Please try again"
    end
  end

  def show
    @posts = tagged
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.user.username), notice: "Post Deleted"
  end

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
    if @posts.nil?
      redirect_to explore_posts_path, notice: "No posts with that tag"
    else
      return @posts
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :tag_list, comments_attributes: [:body])
  end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user

    def show
      @post = @user.posts.with_attached_image.find(params[:id])
      @comments = @post.comments.order(created_at: :desc).limit(5)
      @comment = @post.comments.new
    end

    private

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?

    def set_user
      @user = User.find_by_username!(params[:user_username])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(username: params[:username])
    @posts = @user.posts.with_attached_image.order(created_at: :desc)
  end
end

app/views/users/posts/show.html.erb
<div class="row mt-5">
  <div class="col-sm-8 mx-auto">
    <div class="card shadow-sm">
      <div class="card-img-top py-3 px-3">
        <%= image_tag @post.image, style: "width: 100%" %>
      </div>
      <div class="card-footer mt-5 card-text">
        <div class="d-flex align-items-enter justify-content-between">
          <h5>
            <%= image_tag avatar_url_for(@post.user, size: 32), class: "rounded-circle mr-2" %>
            <%= link_to @post.user.username, user_path(@post.user.username), class: "text-muted" %>
            <% if current_user.present? && @post.user_id == current_user.id %>
              <small>
                <%= link_to "Delete", post_path(@post), class: "btn btn-sm btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
              </small>
            <% end %>
          </h5>
          <div data-behavior="post_<%= @post.id %>_likes">
            <%= render(partial: "posts/likes", locals: { post: @post }) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-3 mb-5">
  <div class="col-sm-8 mx-auto">
    <h3 class="mt-3 mb-4">Comments</h3>

    <div class="card shadow-sm" data-controller="comments-list" data-target="comments-list.postId" data-post-id="<%= @post.id %>">
      <div class="card-body py-4">
        <div data-target="comments-list.commentList">
          <% if @comments.any? %>
            <div data-behavior="pagination-controls" class="text-center">
              <%= render partial: "posts/comments/pagination_links",
                locals: { post: @post, last_result: @comments.reverse.first } %>
            </div>
            <%= render(partial: "posts/comments/comment", collection: @comments.reverse) %>
          <% else %>
            <h6 data-target="comments-list.blankslateText">No comments yet.</h6>
          <% end %>
        </div>
      </div>

      <div class="card-footer py-3">
        <%= render("posts/comments/form", post: @post, comment: @comment) %>
      </div>
    </div>
  </div>
</div>