config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :followers, only: [:create, :destroy], param: :user_id

  resources :posts do
    collection do
      get 'explore'
      get 'tagged'
    end
    resource :likes, only: [:create, :destroy], module: :posts
    resources :comments, only: [:create, :new, :show, :destroy], module: :posts
  end

  resources :users, only: [:show], param: :username, path: '' do
    resources :posts, only: [:show], module: :users
  end

  # get 'posts/tagged', to: "posts#tagged", as: :tagged

  root to: 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  has_one_attached :avatar

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy
  has_many :following, through: :following_relationships, source: :following

  def likes?(likeable)
    likeable.likes.where(user_id: id).any?
  end

  def follow(user_id)
    following_relationships.find_or_create_by(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.where(following_id: user_id).destroy_all
  end

  def follows?(user_id)
    following_relationships.where(following_id: user_id).any?
  end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user

    def show
      @post = @user.posts.with_attached_image.find(params[:id])
      @comments = @post.comments.order(created_at: :desc).limit(5)
      @comment = @post.comments.new
    end

    private

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?

    def set_user
      @user = User.find_by_username!(params[:user_username])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(username: params[:username])
    @posts = @user.posts.with_attached_image.order(created_at: :desc)
  end
end

app/views/users/_follow_button.html.erb
<% unless user == current_user %>
  <% if current_user.follows?(user.id) %>
    <%= link_to "Unfollow", follower_path(user_id: user.id),
      method: :delete,
      remote: true,
      data: { disable_with: "Unfollowing..." },
      class: "btn btn-primary btn-sm" %>
  <% else %>
    <%= link_to "Follow", followers_path(user_id: user.id),
      method: :post,
      remote: true,
      data: { disable_with: "Following..." },
      class: "btn btn-outline-primary btn-sm" %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
  <div class="media mr-5 align-self-start">
    <%= image_tag avatar_url_for(@user, size: 128), class: "rounded-circle mr-4" %>
  </div>
  <div class="media">
    <div class="media-body">
      <div class="d-flex flex-row align-items-center justify-content-between">
          <h1>
            <%= @user.username %>
            <%= link_to "Edit", edit_user_registration_path,
            class: "btn btn-secondary btn-sm ml-3" if current_user.id == @user.id %>
          </h1>

          <div class="ml-3" data-behavior="user_<%= @user.id %>_follow_button">
            <%= render "users/follow_button", user: @user %>
          </div>
      </div>
      <div class="d-flex flex-row align-items-center justify-content-between my-2">
        <h5 class="mr-2">
          <strong><%= @user.posts.count %> <small>posts</small></strong>
        </h5>
        <h5 class="mr-2">
          <strong><%= @user.followers.count %> <small>followers</small></strong>
        </h5>
        <h5 class="mr-2">
          <strong><%= @user.following.count %> <small>following</small></strong>
        </h5>
      </div>

      <% if @user.name.present? %>
        <strong><%= @user.name %></strong>
      <% end %>

      <% if @user.bio.present? %>
        <small>
          <p class="m-0"><%= simple_format(@user.bio) %></p>
        </small>
      <% end %>
    </div>
  </div>
</div>

<div class="d-block align-items-center justify-content-center mt-5">
  <h2 class="text-center mb-4">Posts</h2>

  <% if @posts.any? %>
    <% @posts.each_slice(3) do |slice| %>
      <div class="row mb-3">
        <% slice.each do |post| %>
          <div class="col-sm-4">
            <div class="card">
              <div class="card-img-top">
                <%= link_to user_post_path(post.user.username, post.id) do %>
                  <%= image_tag post.image.variant(resize_to_fill: [250, 250]), style: "width: 100%" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
    <% end %>
  <% else %>
    No posts yet!
  <% end %>
</div>