config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :followers, only: [:create, :destroy], param: :user_id

  resources :posts do
    collection do
      get 'explore'
      get 'tagged'
    end
    resource :likes, only: [:create, :destroy], module: :posts
    resources :comments, only: [:create, :new, :show, :destroy], module: :posts
  end

  resources :users, only: [:show], param: :username, path: '' do
    resources :posts, only: [:show], module: :users
  end

  # get 'posts/tagged', to: "posts#tagged", as: :tagged

  root to: 'welcome#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <%= link_to "Railsgram", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Explore", explore_posts_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Upload", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user.username), class: "nav-link" do %>
              <%= image_tag avatar_url_for(current_user, size: 24), class: "rounded-circle mr-1" %>
              <%= current_user.username %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>