config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :followers, only: [:create, :destroy], param: :user_id

  resources :posts do
    collection do
      get 'explore'
      get 'tagged'
    end
    resource :likes, only: [:create, :destroy], module: :posts
    resources :comments, only: [:create, :new, :show, :destroy], module: :posts
  end

  resources :users, only: [:show], param: :username, path: '' do
    resources :posts, only: [:show], module: :users
  end

  # get 'posts/tagged', to: "posts#tagged", as: :tagged

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  validates :image, attached: true

  scope :of_followed_users, -> (following_users) { where(user_id: following_users) }

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  accepts_nested_attributes_for :comments, reject_if: proc { |attributes| attributes['body'].blank? }

  acts_as_taggable_on :tags
end

app/controllers/posts/comments_controller.rb
module Posts
  class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @comment = @post.comments.build(comments_params.merge(user: current_user))

      if @comment.save
        PostCommentChannel.broadcast_to(@post, comment_created_params)
        # render partial: 'posts/comments/comment', locals: { comment: @comment }
      else
        render partial: 'posts/comments/error', locals: { comment: @comment }, status: :bad_request
      end
    end

    def show
      @comments = @post.comments
        .where("created_at < ?", DateTime.parse(params[:last_result_timestamp]))
        .order(created_at: :desc)
        .limit(5)
    end

    def destroy
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      PostCommentChannel.broadcast_to(@post, comment_destroyed_params)
    end

    private

    def comment_destroyed_params
      { action: :destroy, comment_id: @comment.id }
    end

    def comment_created_params
      { action: :created, html: comment_html }
    end

    def comment_html
      ApplicationController.renderer.render(
        partial: "posts/comments/comment",
        locals: { comment: @comment, realtime: true },
        format: :html
      )
    end

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comments_params
      params.require(:comment).permit(:body)
    end
  end
end

app/controllers/posts/likes_controller.rb
module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @post.likes.where(user: current_user).first_or_create

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    def destroy
      @post.likes.where(user: current_user).destroy_all

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.of_followed_users(current_user.following).with_attached_image.order(created_at: :desc)
  end

  def explore
    @posts = Post.with_attached_image.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.comments&.first&.user = current_user

    if @post.save
      redirect_to posts_path, notice: "Created Post"
    else
      render :new, notice: "Please try again"
    end
  end

  def show
    @posts = tagged
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.user.username), notice: "Post Deleted"
  end

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
    if @posts.nil?
      redirect_to explore_posts_path, notice: "No posts with that tag"
    else
      return @posts
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :tag_list, comments_attributes: [:body])
  end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user

    def show
      @post = @user.posts.with_attached_image.find(params[:id])
      @comments = @post.comments.order(created_at: :desc).limit(5)
      @comment = @post.comments.new
    end

    private

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?

    def set_user
      @user = User.find_by_username!(params[:user_username])
    end
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <% if f.object.errors.any? %>
    <p>
      <%= pluralize(f.object.errors.count, "error") %> prevented the form from being saved.
    </p>

    <ul>
      <% f.object.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
      <% end %>
    </ul>
  <% end %>
  <%= f.hidden_field :post, value: f.object %>
  <div class="form-group">
    <%= f.label :image, "Your image" %>
    <div class="custom-file">
      <%= f.file_field :image, class: "custom-file-input" %>
      <label class="custom-file-label">
        Select file...
      </label>
    </div>

    <%= f.label :tag_list, "Tags" %>
    <%= f.text_area :tag_list, class: "form_control", placeholder: "Example: waffles" %>

    <%= f.fields_for :comments, f.object.comments.new do |comment_form| %>
      <%= comment_form.label :body, "Comment" %>
      <%= comment_form.text_area :body, class: "form-control",
        placeholder: "Start the convo" %>
    <% end %>

    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_likes.html.erb
<h5 class="text-muted">
  <%= post.likes_count %>
  <% if current_user.present? && current_user.likes?(post) %>
    <%= link_to post_likes_path(post), method: :delete, remote: true do %>
      <svg fill="purple" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true do %>
      <svg fill="grey" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
    <% end %>
  <% end %>
</h5>

app/views/posts/_post.html.erb
<div class="col-sm-4">
  <div class="card">
    <div class="card-img-top">
      <%= link_to user_post_path(post.user.username, post.id) do %>
        <%= image_tag post.image.variant(resize_to_fill: [250, 250]), style: "width: 100%" %>
      <% end %>
    </div>
    <div class="card-body card-text mx-auto">
      <p><% post.tag_list.each do |tag| %>
        <%= link_to tag, tagged_posts_path(tag: tag) %>
      <% end %></p>
      <h5>
        <%= image_tag avatar_url_for(post.user, size: 48), class: "rounded-circle" %>
        <%= link_to post.user.username, user_path(post.user.username) %>
      </h5>
    </div>
  </div>
</div>

app/views/posts/explore.html.erb
<h1 class="mt-5 mb-3">Explore Railsgram</h1>

<% if @posts.any? %>
  <% @posts.each_slice(3) do |slice| %>
    <div class="row mb-3">
      <% slice.each do |post| %>
        <%= render("post", post: post) %>
      <% end %>
    </div>
    <% end %>
<% else %>
  <div class="card">
    <div class="card-body p-5">
      <h5>Hmm... Looks like no one has posted anything!</h5>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1 class="mt-5 mb-3">Your Feed</h1>

<% if @posts.any? %>
  <% @posts.each_slice(3) do |slice| %>
    <div class="row mb-3">
      <% slice.each do |post| %>
        <%= render("post", post: post) %>
      <% end %>
    </div>
    <% end %>
<% else %>
  <div class="card">
    <div class="card-body p-5">
      <h5>No posts! Try following someone new!</h5>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <div class="justify-content-center align-items-center">
    <div class="row">
      <div class="col-md-8 col-lg-8 mx-auto my-5">
        <div class="card shadow-sm">
          <div class="card-body p-5">
            <h2 class="my-3">Share something</h2>

            <hr />

            <%= render "form", post: @post %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/tagged.html.erb
<h1 class="mt-5 mb-3">Tagged Posts</h1>

<% if @posts.any? %>
  <% @posts.each_slice(3) do |slice| %>
    <div class="row mb-3">
      <% slice.each do |post| %>
        <%= render("post", post: post) %>
      <% end %>
    </div>
    <% end %>
<% else %>
  <div class="card">
    <div class="card-body p-5">
      <h5>There are no posts with that tag.</h5>
    </div>
  </div>
<% end %>